CREATE TABLE stud2225(RNO NUMBER(4),SNAME VARCHAR(10),PROGRAM VARCHAR(10),CITY VARCHAR(10));

DESC stud2225;

INSERT INTO stud2225 VALUES(1,'Praveen','BCA','ERODE');
INSERT INTO stud2225 VALUES(2,'Kishore','BCA','SALEM');
INSERT INTO stud2225 VALUES(3,'Krishna','CDF','KARUR');
INSERT INTO stud2225 VALUES(4,'Guru','B.COM','GOBI');
INSERT INTO stud2225 VALUES(5,'Ranjith','CDF','GOBI');
INSERT INTO stud2225 VALUES(6,'Harish','B.COM','SALEM');
INSERT INTO stud2225 VALUES(7,'Naveen','BCA','ERODE');
INSERT INTO stud2225 VALUES(8,'Bharath','CDF','ERODE');

SELECT * FROM stud2225;

SELECT * FROM stud2225 WHERE CITY = 'SALEM';

SELECT * FROM stud2225 ORDER BY PROGRAM, SNAME;
